### ISSUE TITLE
AttributeError: 'ZListener' object has no attribute 'update_service' on update to 0.36.7

### ISSUE THREAD

**Issue by riccardocagnasso** [jstasiak/python-zeroconf#1011]
I get this error on update to 0.36.7

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/phas/virtualenvs/nav/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 538, in run
    self._fire_service_state_changed_event(event)
  File "/home/phas/virtualenvs/nav/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 421, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/home/phas/virtualenvs/nav/lib/python3.9/site-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/home/phas/virtualenvs/nav/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 178, in on_change
    getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
AttributeError: 'ZListener' object has no attribute 'update_service'
```

My application both publish and listen

**Comment by bdraco** [comment]
Listeners must inherit from class ServiceListener
