### ISSUE TITLE
Exception when browsing _services._dns-sd._udp.local.

### ISSUE THREAD

**Issue by billysan** [jstasiak/python-zeroconf#136]
This service name is used for Apple-related products (using Bonjour) - [see here](https://developer.apple.com/library/archive/qa/qa1337/_index.html)

I used the standard examples/browser.py and replaced the service name with "_services._dns-sd._udp.local.", which leads to this exception:

`
Browsing services, press Ctrl-C to exit...

Service _http._tcp.local. of type _services._dns-sd._udp.local. state changed: ServiceStateChange.Added
Exception in thread zeroconf-ServiceBrowser__services._dns-sd._udp.local.:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/zeroconf.py", line 1360, in run
    handler(self.zc)
  File "/usr/local/lib/python3.5/dist-packages/zeroconf.py", line 1308, in <lambda>
    state_change=state_change,
  File "/usr/local/lib/python3.5/dist-packages/zeroconf.py", line 1223, in fire
    h(**kwargs)
  File "browser.py", line 17, in on_service_state_change
    info = zeroconf.get_service_info(service_type, name)
  File "/usr/local/lib/python3.5/dist-packages/zeroconf.py", line 1753, in get_service_info
    info = ServiceInfo(type_, name)
  File "/usr/local/lib/python3.5/dist-packages/zeroconf.py", line 1382, in __init__
    raise BadTypeInNameException
zeroconf.BadTypeInNameException
`

Is there any way I could temporarily do a workaround in zeroconf.py to make it browse properly?

**Comment by AmritasyaPutra** [comment]
Your service name ends with _tcp.local. and service type ends with _udp.local. This should have failed during registration itself.

**Comment by jonfitt** [comment]
I see the same thing. 

The service type "_services._dns-sd._udp.<domain>" is special and will return a PTR list of all the services, where many will be _tcp. See https://tools.ietf.org/html/rfc6763 section 9.

So the returned type will not match the requested type.

It would help to be able to do this so we can browse for "all". Thanks.
