### ISSUE TITLE
Typing issue in 0.21.1

### ISSUE THREAD

**Issue by fake-name** [jstasiak/python-zeroconf#141]
In a clean venv on Ubuntu 16.04 LTS:

```
(venv) scrapeworker@scrape-worker-3:/scraper$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zeroconf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scraper/venv/lib/python3.5/site-packages/zeroconf.py", line 320, in <module>
    OptionalExcInfo = Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

Reverting to zeroconf 0.20.0 fixes the issue.

Possibly related to https://github.com/python/typing/issues/266?

**Comment by jstasiak** [comment]
The newly release 0.21.2 should take care of this, please let us know.

**Comment by fake-name** [comment]
Yep, that seems to have fixed it.

Also, it works on ubuntu 14.04 too (also, apparently I have 14.04 VPSes. Whoops?).
