### ISSUE TITLE
AssertionError inside register_service

### ISSUE THREAD

**Issue by dtantsur** [jstasiak/python-zeroconf#162]
I suspect I'm doing something wrong, but without docs and without a sane error message I have no chances to figure it out. Here is a reproducer:
```python
import logging
import socket
import sys
from time import sleep

from zeroconf import ServiceInfo, Zeroconf

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    if len(sys.argv) > 1:
        assert sys.argv[1:] == ['--debug']
        logging.getLogger('zeroconf').setLevel(logging.DEBUG)

    info = ServiceInfo("_http._tcp.local.",
                       "ironic._http._tcp.local.",
                       socket.inet_aton("127.0.0.1"), 6385)

    zeroconf = Zeroconf()
    print("Registration of a service, press Ctrl-C to exit...")
    zeroconf.register_service(info)
    try:
        while True:
            sleep(0.1)
    except KeyboardInterrupt:
        pass
    finally:
        print("Unregistering...")
        zeroconf.unregister_service(info)
        zeroconf.close()
```
And here is the traceback (using 0.20.0, but reproducible on the latest version as well):
```
Registration of a service, press Ctrl-C to exit...
Traceback (most recent call last):
  File "../_registration.py", line 20, in <module>
    zeroconf.register_service(info)
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 1808, in register_service
    self.send(out)
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 2034, in send
    packet = out.packet()
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 1014, in packet
    overrun_answers += self.write_record(answer, time_)
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 986, in write_record
    record.write(self)
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 568, in write
    out.write_string(self.text)
  File "/usr/lib/python3.7/site-packages/zeroconf.py", line 892, in write_string
    assert isinstance(value, bytes)
AssertionError
```
If it's actually my fault, I suggest improving the error message.

**Comment by dtantsur** [comment]
Update: apparently the crash is caused by omitting `properties` from `ServiceInfo`. Adding an empty dict solves the problem:
```python
import logging
import socket
import sys
from time import sleep

from zeroconf import ServiceInfo, Zeroconf

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    if len(sys.argv) > 1:
        assert sys.argv[1:] == ['--debug']
        logging.getLogger('zeroconf').setLevel(logging.DEBUG)

    info = ServiceInfo("_http._tcp.local.",
                       "ironic._http._tcp.local.",
                       socket.inet_aton("127.0.0.1"), 6385,
                       properties={})

    zeroconf = Zeroconf()
    print("Registration of a service, press Ctrl-C to exit...")
    zeroconf.register_service(info)
    try:
        while True:
            sleep(0.1)
    except KeyboardInterrupt:
        pass
    finally:
        print("Unregistering...")
        zeroconf.unregister_service(info)
        zeroconf.close()
```

**Comment by jstasiak** [comment]
What's the python-zeroconf version you're using?

**Comment by dtantsur** [comment]
Tried with 0.19.1 on Python 2, 0.20.0 on Python 3.7 (Fedora package) and 0.21.3 on Python 3.6.

**Comment by jstasiak** [comment]
Hmm, I thought this was supposed to be handled by https://github.com/jstasiak/python-zeroconf/commit/93210079259bd0973e3b54a90dff971e14abf595

**Comment by bdraco** [comment]
This is still reproducible on `master`

**Comment by bdraco** [comment]
@dtantsur I think the constructor has changed since this example.  It does still hit an assertion when the address is placed in the port.  Does it make sense to have a check ?

```
diff --git a/tests/test_aio.py b/tests/test_aio.py
index 4523ca1..a09d94f 100644
--- a/tests/test_aio.py
+++ b/tests/test_aio.py
@@ -657,3 +657,17 @@ async def test_service_browser_instantiation_generates_add_events_from_cache():
     await browser.async_cancel()
 
     await aiozc.async_close()
+
+
+@pytest.mark.asyncio
+async def test_async_register_service_with_no_properties():
+    zeroconf_registrar = AsyncZeroconf(interfaces=['127.0.0.1'])
+    info = ServiceInfo(
+        "_http._tcp.local.", "ironic._http._tcp.local.", 6385, addresses=[socket.inet_aton("127.0.0.1")]
+    )
+
+    try:
+        task = await zeroconf_registrar.async_register_service(info)
+        await task
+    finally:
+        await zeroconf_registrar.async_close()
diff --git a/zeroconf/_services/info.py b/zeroconf/_services/info.py
index f7ab9e5..a0a299c 100644
--- a/zeroconf/_services/info.py
+++ b/zeroconf/_services/info.py
@@ -126,6 +126,8 @@ class ServiceInfo(RecordUpdateListener):
                 'with socket.inet_pton' % invalid
             )
         self.port = port
+        if port is not None and not isinstance(port, int):
+            raise TypeError("Port must be an integer or None, got %s" % port)
         self.weight = weight
         self.priority = priority
         self.server = server if server else name
```

**Comment by bdraco** [comment]
related https://github.com/jstasiak/python-zeroconf/issues/118
