### ISSUE TITLE
Value None on send causes traceback

### ISSUE THREAD

**Issue by Kane610** [jstasiak/python-zeroconf#172]
Getting this error running Home Assistant component Zeroconf using this library.

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/zeroconf/__init__.py

Print of value om line 905: None

Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 1148, in run
    reader.handle_read(socket_)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 1197, in handle_read
    self.zc.handle_query(msg, _MDNS_ADDR, _MDNS_PORT)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 2104, in handle_query
    self.send(out, addr, port)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 2108, in send
    packet = out.packet()
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 1033, in packet
    overrun_additionals += self.write_record(additional, 0)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 1001, in write_record
    record.write(self)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 491, in write
    out.write_string(self.address)
  File "/Users/r/Documents/Dev/venv37/lib/python3.7/site-packages/zeroconf.py", line 906, in write_string
    assert isinstance(value, bytes)
AssertionError

**Comment by jstasiak** [comment]
Is this still happening to you?

**Comment by Kane610** [comment]
I haven't focused on zeroconf for nearly a year ago I can't really say. We can close this for now if you want

**Comment by jstasiak** [comment]
Cool, thanks for the update.
