### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by probonopd** [jstasiak/python-zeroconf#182]
```
~> uname -a
Haiku shredder 1 hrev53242 Jul 11 2019 19:13:24 x86_64 x86_64 Haiku

~> python
Python 2.7.16 (default, May 25 2019, 04:39:12) 
[GCC 7.3.0] on haiku1
Type "help", "copyright", "credits" or "license" for more information.
>>> import zeroconf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/packages/python-2.7.16-3/.self/non-packaged/lib/python2.7/site-packages/zeroconf.py", line 189
    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax
```

Verified with `xubuntu-18.04-desktop-amd64.iso`:

```
me@host:~$ pip install zeroconf

me@host:~$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import zeroconf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python2.7/site-packages/zeroconf.py", line 189
    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax
```

**Comment by dtantsur** [comment]
Hi! The last version that supported Python 2 was 0.19. Are you sure you're using it?

**Comment by codeezer** [comment]
I am using python 3 still I'm facing a similar issue.
`    def current_time_millis() -> float:
                              ^
SyntaxError: invalid syntax`

**Comment by jstasiak** [comment]
Please provide the exact Python version, python-zeroconf version and full stack trace.

**Comment by codeezer** [comment]
Hello,
Now, I have a different error.

`python Beremiz.py
Traceback (most recent call last):
  File "Beremiz.py", line 225, in <module>
    beremiz = BeremizIDELauncher()
  File "Beremiz.py", line 45, in __init__
    self.app_dir = paths.AbsDir(__file__)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/paths.py", line 39, in AbsDir
    file = AbsFile(file)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/paths.py", line 34, in AbsFile
    file = text(file, sys.getfilesystemencoding())
TypeError: decoding str is not supported`

`>> python --version
Python 3.6.9

>>> import zeroconf
>>> zeroconf.__version__
'0.24.4'`

I bypassed the error line. Then, I faced the following error:
`Traceback (most recent call last):
  File "Beremiz.py", line 226, in <module>
    beremiz.Start()
  File "Beremiz.py", line 220, in Start
    self.InstallExceptionHandler()
  File "Beremiz.py", line 183, in InstallExceptionHandler
    import version
  File "/home/ezer/Documents/research/beremiz/beremiz/version.py", line 224, in <module>
    app_version = app_version + "-" + rev.rstrip()
TypeError: must be str, not bytes`

I then converted the rev.rstrip() to the string. Then, there are multiple error messages as follows:

`Traceback (most recent call last):
  File "Beremiz.py", line 203, in AppStart
    self.BackgroundInitialization()
  File "Beremiz.py", line 136, in BackgroundInitialization
    self.ImportModules()
  File "Beremiz.py", line 179, in ImportModules
    mod = __import__(modname)
  File "/home/ezer/Documents/research/beremiz/beremiz/BeremizIDE.py", line 44, in <module>
    from editors.EditorPanel import EditorPanel
  File "/home/ezer/Documents/research/beremiz/beremiz/editors/EditorPanel.py", line 29, in <module>
    from controls import VariablePanel
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/__init__.py", line 29, in <module>
    from controls.CustomEditableListBox import CustomEditableListBox
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/CustomEditableListBox.py", line 31, in <module>
    class CustomEditableListBox(wx.gizmos.EditableListBox):
AttributeError: module 'wx.gizmos' has no attribute 'EditableListBox'
Traceback (most recent call last):
  File "Beremiz.py", line 203, in AppStart
    self.BackgroundInitialization()
  File "Beremiz.py", line 136, in BackgroundInitialization
    self.ImportModules()
  File "Beremiz.py", line 179, in ImportModules
    mod = __import__(modname)
  File "/home/ezer/Documents/research/beremiz/beremiz/BeremizIDE.py", line 44, in <module>
    from editors.EditorPanel import EditorPanel
  File "/home/ezer/Documents/research/beremiz/beremiz/editors/EditorPanel.py", line 29, in <module>
    from controls import VariablePanel
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/__init__.py", line 29, in <module>
    from controls.CustomEditableListBox import CustomEditableListBox
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/CustomEditableListBox.py", line 31, in <module>
    class CustomEditableListBox(wx.gizmos.EditableListBox):
AttributeError: module 'wx.gizmos' has no attribute 'EditableListBox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ezer/.local/lib/python3.6/site-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "Beremiz.py", line 211, in AppStart
    self.handle_exception(*sys.exc_info(), exit=True)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 140, in handle_exception
    save_bug_report(e_type, e_value, e_traceback, bug_report_path, date)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 115, in save_bug_report
    info['locals'] = format_namespace(exception_locals)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 90, in format_namespace
    return '\n'.join(['%s%s: %s' % (indent, k, repr(v)[:10000]) for k, v in d.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 140, in handle_exception
    save_bug_report(e_type, e_value, e_traceback, bug_report_path, date)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 115, in save_bug_report
    info['locals'] = format_namespace(exception_locals)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 90, in format_namespace
    return '\n'.join(['%s%s: %s' % (indent, k, repr(v)[:10000]) for k, v in d.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'

Original exception was:
Traceback (most recent call last):
  File "Beremiz.py", line 203, in AppStart
    self.BackgroundInitialization()
  File "Beremiz.py", line 136, in BackgroundInitialization
    self.ImportModules()
  File "Beremiz.py", line 179, in ImportModules
    mod = __import__(modname)
  File "/home/ezer/Documents/research/beremiz/beremiz/BeremizIDE.py", line 44, in <module>
    from editors.EditorPanel import EditorPanel
  File "/home/ezer/Documents/research/beremiz/beremiz/editors/EditorPanel.py", line 29, in <module>
    from controls import VariablePanel
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/__init__.py", line 29, in <module>
    from controls.CustomEditableListBox import CustomEditableListBox
  File "/home/ezer/Documents/research/beremiz/beremiz/controls/CustomEditableListBox.py", line 31, in <module>
    class CustomEditableListBox(wx.gizmos.EditableListBox):
AttributeError: module 'wx.gizmos' has no attribute 'EditableListBox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ezer/.local/lib/python3.6/site-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "Beremiz.py", line 211, in AppStart
    self.handle_exception(*sys.exc_info(), exit=True)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 140, in handle_exception
    save_bug_report(e_type, e_value, e_traceback, bug_report_path, date)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 115, in save_bug_report
    info['locals'] = format_namespace(exception_locals)
  File "/home/ezer/Documents/research/beremiz/beremiz/util/ExceptionHandler.py", line 90, in format_namespace
    return '\n'.join(['%s%s: %s' % (indent, k, repr(v)[:10000]) for k, v in d.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by jstasiak** [comment]
I don't see how this stack trace is related to the python-zeroconf project/module in any way though, can you shed some light on this?

**Comment by codeezer** [comment]
Ohhh... I'm on the wrong thread. That's my bad. I have managed to solve this issue. So, I'll delete my comment. Sorry for the trouble.

**Comment by jstasiak** [comment]
No worries, I thought I was not seeing something there. Feel free to leave the comment(s), otherwise the discussion may be weird when someone sees it in the future. :)

**Comment by probonopd** [comment]
Would it be possible to print an error saying Python 3 is needed?
