### ISSUE TITLE
Race condition in ServiceBrowser.__init__()

### ISSUE THREAD

**Issue by Feuermurmel** [jstasiak/python-zeroconf#23]
It seems that there's a race between the thread executing `ServiceBrowser.__init__()` and the new thread executing `ServiceBrowser.run()` I'm using this script:

```py
import zeroconf, socket, threading


def main():
	print(zeroconf.__version__)
	
	z = zeroconf.Zeroconf()
	
	# Register some service.
	z.register_service(
		zeroconf.ServiceInfo(
			'_test._tcp.local.',
			'test._test._tcp.local.',
			socket.inet_aton('127.0.0.1'),
			80,
			properties = { }))
	
	class listener:
		@staticmethod
		def add_service(*args):
			print('add_service():', args)
		
		@staticmethod
		def remove_service(*args):
			print('remove_service():', args)
	
	# Immediately browse for services of the same type.
	z.add_service_listener('_test._tcp.local.', listener)
	
	# Wait forever.
	threading.Event().wait()


if __name__ == '__main__':
	main()
```

When running this, sometimes I get this output:

```
0.17.2
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/Users/michi/Desktop/Abfahrtsanzeiger_Roeschtibach/doorswitch/venv3/lib/python3.4/site-packages/zeroconf.py", line 1063, in run
    handler(self.zc)
  File "/Users/michi/Desktop/Abfahrtsanzeiger_Roeschtibach/doorswitch/venv3/lib/python3.4/site-packages/zeroconf.py", line 1010, in <lambda>
    lambda zeroconf: self._service_state_changed.fire(
AttributeError: 'ServiceBrowser' object has no attribute '_service_state_changed'
```

It seems that the newly started thread tries to access `self._service_state_changed` before it has been initialized by `self.__init__()`.

**Comment by gbiddison** [comment]
If I had write access I would propose this patch:

```diff
diff --git a/zeroconf.py b/zeroconf.py
index 2d67563..2f39984 100644
--- a/zeroconf.py
+++ b/zeroconf.py
@@ -972,7 +972,6 @@ class ServiceBrowser(threading.Thread):
         self.done = False
 
         self.zc.add_listener(self, DNSQuestion(self.type, _TYPE_PTR, _CLASS_IN))
-        self.start()
 
         self._service_state_changed = Signal()
 
@@ -996,6 +995,8 @@ class ServiceBrowser(threading.Thread):
         for h in handlers:
             self.service_state_changed.register_handler(h)
 
+        self.start()
+
     @property
     def service_state_changed(self):
         return self._service_state_changed.registration_interface
```

**Comment by jstasiak** [comment]
Fixed in https://github.com/jstasiak/python-zeroconf/commit/30bd44f04f94a9b26622a7213dd9950ae57df21c. Thanks for the report @Feuermurmel.

**Comment by giupo** [comment]
I have the same problem on OSX 10.11.2: I found out it's enough to move the `threading.start` invocation outside of `ServiceBrowser. __init__` to fix the issue. 

This could break some behaviour, but if it's doable, I will prepare a pull request.
