### ISSUE TITLE
Choked at offset

### ISSUE THREAD

**Issue by bagobones** [jstasiak/python-zeroconf#308]
```
2020-10-11 19:36:58 WARNING (zeroconf-Engine-265) [zeroconf] Choked at offset 381 while unpacking b'\x00\x00\x84\x00\x00\x00\x00\x05\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00!\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x05c#=11\x04ff=1\x14id=37:5A:50:AC:FD:31\x12md=TRADFRI gateway\x06pv=1.1\x04s#=1\x04sf=0\x04ci=2\x0bsh=PUXsOg==\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01F\x00\x00\x00\x1c\x80\x01\x00\x00\x00\x00\x00\x10\x00\xf0>\xb0z\x80\x12\xeaz\x80\x12\xeaz\x80\x12\xea'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 716, in __init__
    self.read_others()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 787, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 848, in read_name
    length = self.data[off]
IndexError: index out of range
```

Was directed here by home assistant issue https://github.com/home-assistant/core/issues/39588 more examples in that issue report.

**Comment by jstasiak** [comment]
Please provide your OS, Python version and python-zeroconf version. I took the data present in the log above and I can't reproduce the warning:

```
~/projects/python-zeroconf% cat x.py 
data = b'\x00\x00\x84\x00\x00\x00\x00\x05\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00!\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x05c#=11\x04ff=1\x14id=37:5A:50:AC:FD:31\x12md=TRADFRI gateway\x06pv=1.1\x04s#=1\x04sf=0\x04ci=2\x0bsh=PUXsOg==\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01F\x00\x00\x00\x1c\x80\x01\x00\x00\x00\x00\x00\x10\x00\xf0>\xb0z\x80\x12\xeaz\x80\x12\xeaz\x80\x12\xea'

from zeroconf import DNSIncoming
print(DNSIncoming(data))

~/projects/python-zeroconf% PYTHONPATH=. python x.py
<DNSIncoming:{id=0, flags=33792, n_q=0, n_ans=5, n_auth=0, n_add=0, questions=[], answers=[record[ptr,in,_hap._tcp.local.]=4500/4499,TRADFRI gateway._hap._tcp.local., record[txt,in-unique,TRADFRI gateway._hap._tcp.local.]=4500/4499,b'\x05c#=11\x04'..., record[srv,in-unique,TRADFRI gateway._hap._tcp.local.]=120/119,:80]}>
```

**Comment by jstasiak** [comment]
Ah, sorry – I forgot to turn on the logging, it's reproducible now:

```
~/projects/python-zeroconf% cat x.py                
data = b'\x00\x00\x84\x00\x00\x00\x00\x05\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00!\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x05c#=11\x04ff=1\x14id=37:5A:50:AC:FD:31\x12md=TRADFRI gateway\x06pv=1.1\x04s#=1\x04sf=0\x04ci=2\x0bsh=PUXsOg==\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01F\x00\x00\x00\x1c\x80\x01\x00\x00\x00\x00\x00\x10\x00\xf0>\xb0z\x80\x12\xeaz\x80\x12\xeaz\x80\x12\xea'

from zeroconf import DNSIncoming
import logging
logging.basicConfig(level=logging.DEBUG)
print(DNSIncoming(data))

~/projects/python-zeroconf% PYTHONPATH=. python x.py
WARNING:zeroconf:Choked at offset 381 while unpacking b'\x00\x00\x84\x00\x00\x00\x00\x05\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00!\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x05c#=11\x04ff=1\x14id=37:5A:50:AC:FD:31\x12md=TRADFRI gateway\x06pv=1.1\x04s#=1\x04sf=0\x04ci=2\x0bsh=PUXsOg==\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01F\x00\x00\x00\x1c\x80\x01\x00\x00\x00\x00\x00\x10\x00\xf0>\xb0z\x80\x12\xeaz\x80\x12\xeaz\x80\x12\xea'
Traceback (most recent call last):
  File "/Users/user/projects/python-zeroconf/zeroconf/__init__.py", line 716, in __init__
    self.read_others()
  File "/Users/user/projects/python-zeroconf/zeroconf/__init__.py", line 787, in read_others
    domain = self.read_name()
  File "/Users/user/projects/python-zeroconf/zeroconf/__init__.py", line 848, in read_name
    length = self.data[off]
IndexError: index out of range
<DNSIncoming:{id=0, flags=33792, n_q=0, n_ans=5, n_auth=0, n_add=0, questions=[], answers=[record[ptr,in,_hap._tcp.local.]=4500/4499,TRADFRI gateway._hap._tcp.local., record[txt,in-unique,TRADFRI gateway._hap._tcp.local.]=4500/4499,b'\x05c#=11\x04'..., record[srv,in-unique,TRADFRI gateway._hap._tcp.local.]=120/119,:80]}>
```

**Comment by jstasiak** [comment]
The message received seems to be correctly identified as malformed, I tested it with dnspython to confirm:

```python
>>> import dns.message
>>> data = b'\x00\x00\x84\x00\x00\x00\x00\x05\x00\x00\x00\x00\x04_hap\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x11\x94\x00!\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x05c#=11\x04ff=1\x14id=37:5A:50:AC:FD:31\x12md=TRADFRI gateway\x06pv=1.1\x04s#=1\x04sf=0\x04ci=2\x0bsh=PUXsOg==\x0fTRADFRI gateway\x04_hap\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x01F\x00\x00\x00\x1c\x80\x01\x00\x00\x00\x00\x00\x10\x00\xf0>\xb0z\x80\x12\xeaz\x80\x12\xeaz\x80\x12\xea'
>>> 
>>> 
>>> 
>>> dns.message.from_wire(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.ve38/lib/python3.8/site-packages/dns/message.py", line 933, in from_wire
    m = reader.read()
  File "/Users/user/.ve38/lib/python3.8/site-packages/dns/message.py", line 857, in read
    self._get_section(MessageSection.ANSWER, ancount)
  File "/Users/user/.ve38/lib/python3.8/site-packages/dns/message.py", line 798, in _get_section
    with self.parser.restrict_to(rdlen):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/user/.ve38/lib/python3.8/site-packages/dns/wire.py", line 64, in restrict_to
    raise dns.exception.FormError
dns.exception.FormError: DNS message is malformed.
```

**Comment by bagobones** [comment]
ok. Is the malformed message from the device being discovered? There appear to be numerous examples in the HA thread. Should this not just trap the malformed data and toss a warning instead of dropping an error and a causing a traceback?

**Comment by jstasiak** [comment]
Ye, it's a malformed message received from the network, it seems.


> Should this not just trap the malformed data and toss a warning instead of dropping an error and a causing a traceback?

It does exactly this – catches the error and logs a warning (with a stack trace, but that doesn't change anything): https://github.com/jstasiak/python-zeroconf/blob/6ab0cd0a0446f158a1d8a64a3bc548cf9e103179/zeroconf/__init__.py#L746

**Comment by bagobones** [comment]
So should I just toss this back to the HA devs as working as intended and for them to set a lower priority for the messages? I assume if zeroconf is reaching out to anything that is probable that malformed messages will be the norm during discovery and should be less of an error and more of an ignorable warning unless something isn't being discovered correctly.

If I am understanding correctly zeroconf is working as intended..

**Comment by jstasiak** [comment]
For all intents and purposes it's not an error but an ignorable warning – the relevant internal errors are intercepted, the code keeps running, there are no crashes, the warning gets logged and the client code never learns about it. There's always gonna be some tension between people wanting for cases like this to be silently ignored and people wanting to know about them, I don't have a good answer here.

I believe it's working as intended unless we're shown a valid DNS payload that fails to be parsed and causes the message above.

**Comment by bdraco** [comment]
One thing we could do is make the error message more friendly to explain what is going on.  The current message leads users to believe the problem is in zeroconf when it is really a problem with the device on the network. Admittedly, that was my first thought as well given the message is that it `choked`

**Comment by bdraco** [comment]
It turns out we generate invalid packets because we don't reset at the start of each call to `packets`

The below packet is generated from zeroconf

```
2020-10-27 17:32:17 WARNING (zeroconf-Engine-256) [zeroconf] Choked at offset 1434 while unpacking b'\x00\x00\x84\x00\x00\x00\x00\x01\x00\x00\x00\x1b\x17HASS Bridge 3K9A C2582A\x04_hap\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge 3K9A\x06pv=1.0\x14id=E2:AA:5B:C2:58:2A\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=44wQQA==\x17HASS Bridge WLTF 4BE61F\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xca}\xc0\x95\xc0\x95\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x13md=HASS Bridge WLTF\x06pv=1.0\x14id=E0:E7:98:4B:E6:1F\x04c#=2\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=7T8wEg==\xc0\x95\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x16FrontdoorCamera 8941D1\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xd6r\xc12\xc12\x00\x10\x80\x01\x00\x00\x11\x94\x00T\x12md=FrontdoorCamera\x06pv=1.0\x14id=9F:B7:DC:89:41:D1\x04c#=2\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=BLLU2A==\xc12\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge ZC8X FF413D\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcau\xc1\xcd\xc1\xcd\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge ZC8X\x06pv=1.0\x14id=96:14:45:FF:41:3D\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=03VqpA==\xc1\xcd\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x14Master Bed TV CEDB27\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcav\xc2k\xc2k\x00\x10\x80\x01\x00\x00\x11\x94\x00T\x10md=Master Bed TV\x06pv=1.0\x14id=9E:B7:44:CE:DB:27\x05c#=18\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=86aNKg==\xc2k\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x15Living Room TV 921B77\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcay\xc3\x04\xc3\x04\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x11md=Living Room TV\x06pv=1.0\x14id=11:61:E7:92:1B:77\x05c#=17\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=7sni9Q==\xc3\x04\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x15Snooze Room TV 6B89B0\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xca{\xc3\x9f\xc3\x9f\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x11md=Snooze Room TV\x06pv=1.0\x14id=5F:D5:70:6B:89:B0\x05c#=17\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=+sYFpA==\xc3\x9f\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge W9DN 5B5CC5\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xca|\xc4:\xc4:\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge W9DN\x06pv=1.0\x14id=11:8E:DB:5B:5C:C5\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=/0+YrA==\xc4:\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\xc0\x0c\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcaz\xc0\x0c\xc0\x0c\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge 3K9A\x06pv=1.0\x14id=E2:AA:5B:C2:58:2A\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=44wQQA==\xc0\x0c\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge ZJWH FF5137\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcax\xc5^\xc5^\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\xc5\x9a\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 741, in __init__
    self.read_others()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 812, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 886, in read_name
    raise IncomingDecodeError("Bad domain name (circular) at %s" % (off,))
zeroconf.IncomingDecodeError: Bad domain name (circular) at 1434
```

```
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.message
>>> data = b'\x00\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x1e\x17HASS Bridge WLTF 4BE61F\x04_hap\x04_tcp\x05local\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x16FrontdoorCamera 8941D1\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xd6r\xc0C\xc0C\x00\x10\x80\x01\x00\x00\x11\x94\x00T\x12md=FrontdoorCamera\x06pv=1.0\x14id=9F:B7:DC:89:41:D1\x04c#=2\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=BLLU2A==\xc0C\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge ZC8X FF413D\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcau\xc0\xde\xc0\xde\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge ZC8X\x06pv=1.0\x14id=96:14:45:FF:41:3D\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=03VqpA==\xc0\xde\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x14Master Bed TV CEDB27\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcav\xc1|\xc1|\x00\x10\x80\x01\x00\x00\x11\x94\x00T\x10md=Master Bed TV\x06pv=1.0\x14id=9E:B7:44:CE:DB:27\x05c#=18\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=86aNKg==\xc1|\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x15Living Room TV 921B77\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcay\xc2\x15\xc2\x15\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x11md=Living Room TV\x06pv=1.0\x14id=11:61:E7:92:1B:77\x05c#=17\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=7sni9Q==\xc2\x15\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x15Snooze Room TV 6B89B0\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xca{\xc2\xb0\xc2\xb0\x00\x10\x80\x01\x00\x00\x11\x94\x00U\x11md=Snooze Room TV\x06pv=1.0\x14id=5F:D5:70:6B:89:B0\x05c#=17\x04s#=1\x04ff=0\x05ci=31\x04sf=0\x0bsh=+sYFpA==\xc2\xb0\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge W9DN 5B5CC5\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xca|\xc3K\xc3K\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge W9DN\x06pv=1.0\x14id=11:8E:DB:5B:5C:C5\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=/0+YrA==\xc3K\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge 3K9A C2582A\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcaz\xc3\xe9\xc3\xe9\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge 3K9A\x06pv=1.0\x14id=E2:AA:5B:C2:58:2A\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=44wQQA==\xc3\xe9\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge ZJWH FF5137\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcax\xc4\x87\xc4\x87\x00\x10\x80\x01\x00\x00\x11\x94\x00V\x13md=HASS Bridge ZJWH\x06pv=1.0\x14id=01:6B:30:FF:51:37\x05c#=12\x04s#=1\x04ff=0\x04ci=2\x04sf=0\x0bsh=bXNlGw==\xc4\x87\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x1dAlexanderHomeAssistant 74651D\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xd6\x1b\xc5%\xc5%\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\x17HASS Bridge OS95 39C053\xc0$\x00!\x80\x01\x00\x00\x00x\x00\x08\x00\x00\x00\x00\xcaw\xc5g\xc5g\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05\xc5\xd3\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\xd0\x05'
>>> dns.message.from_wire(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/dns/message.py", line 933, in from_wire
    m = reader.read()
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/dns/message.py", line 859, in read
    self._get_section(MessageSection.ADDITIONAL, adcount)
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/dns/message.py", line 777, in _get_section
    absolute_name = self.parser.get_name()
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/dns/wire.py", line 49, in get_name
    name = dns.name.from_wire_parser(self)
  File "/Users/bdraco/Library/Python/3.8/lib/python/site-packages/dns/name.py", line 990, in from_wire_parser
    raise BadPointer
dns.name.BadPointer: A DNS compression pointer points forward instead of backward.
>>> 
```

**Comment by brouwer** [comment]
I have upgraded to 0.28.8, but am still getting these:
```
2021-02-17 14:48:09 WARNING (zeroconf-Engine-1748780128) [zeroconf] Choked at offset 338 while unpacking b'\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x0czwFDE6F89901\x05local\x00\x00\xff\x00\x01\x013\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010
\x010\x010\x010\x010\x010\x010\x010\x01a\x01a\x01a\x01a\x010\x010\x01d\x01f\x03ip6\x04arpa\x00\x00\xff\x00\x01\x010\x010\x010\x010\x07in-addr\xc0h\x00\xff\x00\x01\x0czwFDE6F89901\x05local\x00\x00\x1c\x00\x01\x00\x00\x00x\x00\x10\xfd\x00\xaa\xaa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x03\x013\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x010\x01a\x01a\x01a\x01a\x010\x010\x01d\x01f\x03ip6\x04arpa\x00\x00\x0c\x00\x01\x00\x00\x00x\x00\x14\x0czwFDE6F89901\x05local\x00\x010\x010\x010\x010\x07in-addr\x
04arpa\x00\x00\x0c\x00\x01\x00\x00\x00x\x00\x14\x0czwFDE6F89901\x05local\x00'
Traceback (most recent call last):
  File "/root/kardia/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 745, in __init__
    self.read_others()
  File "/root/kardia/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 816, in read_others
    domain = self.read_name()
  File "/root/kardia/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 877, in read_name
    length = self.data[off]
IndexError: index out of range
```

Seems to be caused by discoery of Z/IP Gateway which is running on the same raspberry pi. (I am using Python 3.7.6)
Apart from just ignoring these warnings, is there any other fix?
