### ISSUE TITLE
self.services can change during iteration in `handle_query`

### ISSUE THREAD

**Issue by bdraco** [jstasiak/python-zeroconf#316]
```
2020-10-25 18:57:15 ERROR (zeroconf-Engine-257) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1355, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1448, in handle_read
    self.zc.handle_query(msg, None, _MDNS_PORT)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2780, in handle_query
    for service in self.services.values():
RuntimeError: dictionary changed size during iteration
```

This ends up being an uncaught exception as well so `zeroconf` dies off.

I'm opening the issue so I don't forget to look into it.

**Comment by bdraco** [comment]
probably need to switch this to `dict` since that should be atomic.
