### ISSUE TITLE
ImportError: cannot import name ServiceBrowser

### ISSUE THREAD

**Issue by nejdetckenobi** [jstasiak/python-zeroconf#90]
Hi,

I am trying to run the code below:
```
from six.moves import input
from zeroconf import ServiceBrowser, Zeroconf


class MyListener(object):

    def remove_service(self, zeroconf, type, name):
        print("Service %s removed" % (name,))

    def add_service(self, zeroconf, type, name):
        info = zeroconf.get_service_info(type, name)
        print("Service %s added, service info: %s" % (name, info))


zeroconf = Zeroconf()
listener = MyListener()
browser = ServiceBrowser(zeroconf, "_http._tcp.local.", listener)
try:
    input("Press enter to exit...\n\n")
finally:
    zeroconf.close()

```
And getting the error below:

```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zeroconf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zeroconf.py", line 2, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
ImportError: cannot import name ServiceBrowser
```

**Comment by stephenrauch** [comment]
You file is named zeroconf.py.  Thus you are attempting to import yourself.  You need to rename your file.
