### ISSUE TITLE
Bash on Windows, socket.error: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by nils-werner** [jstasiak/python-zeroconf#91]
Under Bash on Windows, when simply creating a `zeroconf.Zeroconf()` object, I see the following error:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import zeroconf as z
>>> z.Zeroconf()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nils/.local/lib/python2.7/site-packages/zeroconf.py", line 1513, in __init__
    self._listen_socket = new_socket()
  File "/home/nils/.local/lib/python2.7/site-packages/zeroconf.py", line 1472, in new_socket
    s.setsockopt(socket.SOL_SOCKET, reuseport, 1)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
```

using zeroconf version 0.17.6

It seems to be linked to the use of `SO_REUSEPORT` [[1]](http://stackoverflow.com/questions/13637121/so-reuseport-is-not-defined-on-windows-7) [[2]](http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t?rq=1)

```
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
```

I don't know enough about all those socket options, but the following two options are thrown around in the stackoverflow answers above, and they both work:

```
>>> s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
>>> s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

**Comment by bdraco** [comment]
We have a guard here now https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_utils/net.py#L202
