### ISSUE TITLE
Service discovery over IPv6 link local address on Windows fails with [WinError 10022] An invalid argument was supplied

### ISSUE THREAD

**Issue by lokesh2019** [jstasiak/python-zeroconf#932]
I am trying to discover services on a Windows Server 2019 machine with Python 3.8.10 and zeroconf version 0.33.2, on an interface with a link-local IPv6 address.

Code:
```
from zeroconf import ZeroconfServiceTypes, IPVersion
import logging

logging.basicConfig(level=logging.DEBUG)
print('\n'.join(ZeroconfServiceTypes.find(ip_version=IPVersion.V6Only, interfaces=["fe80::7832:2ab4:405e:f658"])))
```

To confirm the interface address:
```
Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7832:2ab4:405e:f658%19
   Autoconfiguration IPv4 Address. . : 169.254.246.88
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
```

Output:
I have added an `assert False` here to get better stack trace for the error: https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_core.py#L325

```
PS C:\users\Administrator\Desktop> python .\test.py
DEBUG:asyncio:Using proactor: IocpProactor
fileno: 632
flags: 0
addr: ('ff02::fb', 5353)
WARNING:zeroconf:Error with socket 632: [WinError 10022] An invalid argument was supplied
ERROR:asyncio:Exception in callback _ServiceBrowserBase._async_send_ready_queries_schedule_next()
handle: <TimerHandle when=28746.89011401367 _ServiceBrowserBase._async_send_ready_queries_schedule_next()>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 526, in _loop_writing
    self._write_fut = self._loop._proactor.sendto(self._sock,
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 516, in sendto
    ov.WSASendTo(conn.fileno(), buf, flags, addr)
OSError: [WinError 10022] An invalid argument was supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\site-packages\zeroconf\_services\browser.py", line 478, in _async_send_ready_queries_schedule_next
    self.zc.async_send(out, addr=self.addr, port=self.port)
  File "C:\Program Files\Python38\lib\site-packages\zeroconf\_core.py", line 759, in async_send
    transport.sendto(packet, (real_addr, port or _MDNS_PORT, *v6_flow_scope))
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 499, in sendto
    self._loop_writing()
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 530, in _loop_writing
    self._protocol.error_received(exc)
  File "C:\Program Files\Python38\lib\site-packages\zeroconf\_core.py", line 325, in error_received
    assert False
AssertionError
```

The error I need help with is: 
`OSError: [WinError 10022] An invalid argument was supplied`

Thank you.

**Comment by bdraco** [comment]
Seems like windows can't handle the empty tuple.

**Comment by bdraco** [comment]
Does it work with `transport.sendto(packet, 0, (real_addr, port, *v6_flow_scope) if v6_flow_scope else (real_addr, port))`?

We should be going through the transport layer instead of accessing the socket directly.  I think that will fail in newer python

**Comment by lokesh2019** [comment]
Indeed it has to do with the empty tuple. I have a fix ready, just need to do some more testing. I'll raise a PR this week.

**Comment by lokesh2019** [comment]
Raised PR https://github.com/jstasiak/python-zeroconf/pull/965

**Comment by bdraco** [comment]
As there is some risk (hopefully very small) of unexpected impact for IPv6 configurations that I can't envision I'm going to bump the version to 0.36.0 and mark it `Technically backwards incompatible`

I'll release 0.36.0 shortly.
