### ISSUE TITLE
0.34.0: pytest warnings

### ISSUE THREAD

**Issue by kloczek** [jstasiak/python-zeroconf#948]
I'm trying to package your module as rpm packag. So I'm using typical in such case build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

May I ask for help because few units are failing:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-zeroconf-0.34.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-zeroconf-0.34.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0, configfile: setup.cfg, testpaths: tests
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, toolbox-0.5, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, hypothesis-6.14.4, xprocess-0.18.1, black-0.3.12, checkdocs-2.7.1, anyio-3.3.0, Faker-8.11.0, asyncio-0.15.1, trio-0.7.0, httpbin-1.0.0, subtests-0.5.0, relaxed-1.1.5
collected 239 items

tests/test_asyncio.py ......................                                                                                                                         [  9%]
tests/test_cache.py ...............                                                                                                                                  [ 15%]
tests/test_core.py ......s.................                                                                                                                          [ 25%]
tests/test_dns.py ......................                                                                                                                             [ 34%]
tests/test_exceptions.py .........                                                                                                                                   [ 38%]
tests/test_handlers.py .....................                                                                                                                         [ 47%]
tests/test_history.py ..                                                                                                                                             [ 48%]
tests/test_init.py .......                                                                                                                                           [ 51%]
tests/test_logger.py ....                                                                                                                                            [ 52%]
tests/test_protocol.py ............................................                                                                                                  [ 71%]
tests/test_services.py ...                                                                                                                                           [ 72%]
tests/test_updates.py .                                                                                                                                              [ 72%]
tests/services/test_browser.py ...................                                                                                                                   [ 80%]
tests/services/test_info.py ...............                                                                                                                          [ 87%]
tests/services/test_registry.py .....                                                                                                                                [ 89%]
tests/services/test_types.py ....                                                                                                                                    [ 90%]
tests/utils/test_asyncio.py ......                                                                                                                                   [ 93%]
tests/utils/test_name.py ..                                                                                                                                          [ 94%]
tests/utils/test_net.py ...........s..                                                                                                                               [100%]

============================================================================= warnings summary =============================================================================
tests/test_core.py::test_open_close_twice_from_async
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3a95bdfdc0>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 123, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 148, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_core.py::test_multiple_sync_instances_stared_from_async_close
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3a95de2f40>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 123, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 148, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_handlers.py::test_qu_response
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3a85921140>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/selectors.py", line 72, in __getitem__
      return self._selector._fd_to_key[fd]
  KeyError: 40

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 123, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_core.py", line 148, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/services/test_browser.py::test_service_browser_listeners_no_update_service
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_services/browser.py:169: FutureWarning: <tests.services.test_browser.test_service_browser_listeners_no_update_service.<locals>.MyServiceListener object at 0x7f3a95a11fa0> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
    warnings.warn(

tests/services/test_browser.py::test_service_browser_listeners_no_update_service
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread zeroconf-ServiceBrowser-_hap._tcp-2438385

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_services/browser.py", line 535, in run
      self._fire_service_state_changed_event(event)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_services/browser.py", line 422, in _fire_service_state_changed_event
      self._service_state_changed.fire(
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_services/__init__.py", line 55, in fire
      h(**kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.34.0/zeroconf/_services/browser.py", line 178, in on_change
      getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
  AttributeError: 'MyServiceListener' object has no attribute 'update_service'

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/test_core.py:152: apple_p2p happy path only testable on mac
SKIPPED [1] tests/utils/test_net.py:136: System has SO_REUSEPORT
========================================================== 237 passed, 2 skipped, 5 warnings in 94.14s (0:01:34) ===========================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by bdraco** [comment]
It looks like all the tests are passing, the warnings are from the tests that make sure there is no deadlock when zeroconf is closed out while an operation is still in progress.  That is expected to generate some warnings.

`237 passed, 2 skipped, 5 warnings in 94.14s`

**Comment by kloczek** [comment]
Aa .. so looks like nothing to worry about :)
If that is true feel free to close this ticket.

**Comment by bdraco** [comment]
All of the ones you posted are expected so they are safe to ignore 👍

**Comment by kloczek** [comment]
Thank you :)

**Comment by kloczek** [comment]
Now after upgrade pytest to latest one I see much more warnings
<details>

```console
=============================== warnings summary ===============================
tests/test_asyncio.py::test_async_with_sync_passed_in_closed_in_async
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3f76e64dc0>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 139, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 159, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_asyncio.py::test_async_service_registration
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/info.py:197: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    for address in value:
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py::test_async_service_registration
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/info.py:197: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    for address in value:
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py::test_async_service_registration
tests/test_core.py::test_guard_against_oversized_packets
tests/test_handlers.py::test_qu_response
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=11>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py: 1 warning
tests/test_core.py: 7 warnings
tests/test_handlers.py: 4 warnings
tests/test_init.py: 1 warning
tests/services/test_browser.py: 5 warnings
tests/services/test_info.py: 3 warnings
tests/utils/test_asyncio.py: 1 warning
tests/utils/test_net.py: 1 warning
  /usr/lib64/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_open_close_twice_from_async
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3f76883540>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 139, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 159, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_core.py::test_multiple_sync_instances_stared_from_async_close
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3f768837c0>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 139, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 159, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=22, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=23, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_dns.py:368: ResourceWarning: unclosed <socket.socket fd=24, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    super().__init__(name, type_, class_, ttl, created)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=13>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=15>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_guard_against_oversized_packets
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=23>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_exceptions.py::Exceptions::test_invalid_addresses
  /usr/lib64/python3.8/asyncio/futures.py:354: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    def _set_state(future, other):
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_exceptions.py::Exceptions::test_invalid_addresses
  /usr/lib64/python3.8/asyncio/futures.py:354: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    def _set_state(future, other):
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /usr/lib64/python3.8/selectors.py:74: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    raise KeyError("{!r} is not registered".format(fileobj)) from None
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /usr/lib64/python3.8/selectors.py:74: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    raise KeyError("{!r} is not registered".format(fileobj)) from None
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f3f766279c0>

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1349, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 139, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py", line 159, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 1351, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.8/asyncio/selector_events.py", line 692, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_init.py::Names::test_verify_name_change_with_lots_of_names
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport fd=11>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_init.py::Names::test_verify_name_change_with_lots_of_names
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_core.py:159: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    transport, protocol = await loop.create_datagram_endpoint(lambda: AsyncListener(self.zc), sock=s)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_init.py::Names::test_verify_name_change_with_lots_of_names
  /usr/lib64/python3.8/asyncio/selector_events.py:696: ResourceWarning: unclosed transport <_SelectorDatagramTransport fd=12>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/services/test_browser.py::test_service_browser_listeners_no_update_service
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread zeroconf-ServiceBrowser-_hap._tcp-483256

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/browser.py", line 547, in run
      self._fire_service_state_changed_event(event)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/browser.py", line 428, in _fire_service_state_changed_event
      self._service_state_changed.fire(
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/__init__.py", line 54, in fire
      h(**kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/browser.py", line 188, in on_change
      getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.47.3/src/zeroconf/_services/__init__.py", line 45, in update_service
      raise NotImplementedError()
  NotImplementedError

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/utils/test_net.py::test_disable_ipv6_only_or_raise
  /usr/lib/python3.8/site-packages/_pytest/python.py:200: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>
    result = testfunction(**testargs)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/utils/test_net.py::test_add_multicast_member
  /usr/lib64/python3.8/unittest/mock.py:2076: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>
    self.name = name
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
SKIPPED [1] tests/test_core.py:154: apple_p2p happy path only testable on mac
SKIPPED [1] tests/utils/test_net.py:136: System has SO_REUSEPORT
=========== 267 passed, 2 skipped, 53 warnings in 106.36s (0:01:46) ============
```
</details>
