### ISSUE TITLE
Multiple warn logs of "Choked at offset"

### ISSUE THREAD

**Issue by Quentame** [jstasiak/python-zeroconf#993]
I know those logs are warnings but I think it's worth notice it.
Perhaps we may create multiple issues for each message type, you tell me.

I don't know the project well, just the general purpose, so I may miss something.
I'll try to respond to your questions ASAP.

### What installation are you running?

I am having issues for about a month in Home Assistant on a Docker container, the current version of the zeroconf dependency is `0.36.2`.

Installed version of Home Assistant : https://github.com/home-assistant/core/releases/tag/2021.9.6 (zeroconf version `0.36.2`)
But I've noticed it from the 2021.9 beta : https://github.com/home-assistant/core/releases/tag/2021.9.0b0 (zeroconf version `0.36.0`)

Logs below.

#### Home Assistant System health

version | core-2021.9.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 4.4.59+
arch | x86_64
timezone | Europe/Paris

#### Home Assistant summaries

- IncomingDecodeError: DNS compression type [X] is unknown at [Y]
```shell
Logger: zeroconf
Source: /usr/local/lib/python3.9/site-packages/zeroconf/_logger.py:52
First occurred: 19 septembre 2021, 1:30:06 (6 occurrences)
Last logged: 5:43:27

- Choked at offset 12 while unpacking b'6.Y^:VN\x0cH\x0f}G\nt&;\x1dtBMn*\\\x01km6<\xa7\xcd'
- Choked at offset 12 while unpacking b"}.+u\x1f!]Kl wSH)H?nj<XK3E*\x13\n&9\x11\x10i\x0f$\x14\x04D5b\x0f!\x02\x06tJ0=\n\x1e'Fwry<\x1d\x0cFCEWS.fxCk<xMK\x1aOQ\x0e\x1a\x01Ki\xce"
- Choked at offset 12 while unpacking b"y.{\x00'|S:qw\x15\x17/\x7fwGad\x17;D@5\t#\x7f\x1f\x13p\x1fld\x135mZ\x021a\n\x12bh`\r=;\x06\x04Z\x19\x07f?\x055Ra.;t"
- Choked at offset 12 while unpacking b'\x16\x03\x01\x00\xee\x01\x00\x00\xea\x03\x03whv\xe7\xb7\xc4@\xb7\xbe\xc0\xba\x1911~\xb6\x1f)U\xff\x967\xb4F\xe1\xf3\x85%\x97Q\xd7\xa1 K\x0f\x86\x11/\x9fk\xcd\xfeWi)r\xcc\xeb\x16\xb5\xa3yx)R\xec\xb3V\x02B\xa7\x8e\xa2E\xfe\x00&\xc0/\xc00\xc0+\xc0,\xcc\xa8\xcc\xa9\xc0\x13\xc0\t\xc0\x14\xc0\n\x00\x9c\x00\x9d\x00/\x005\xc0\x12\x00\n\x13\x01\x13\x03\x13\x02\x01\x00\x00{\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\n\x00\n\x00\x08\x00\x1d\x00\x17\x00\x18\x00\x19\x00\x0b\x00\x02\x01\x00\x00\r\x00\x1a\x00\x18\x08\x04\x04\x03\x08\x07\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x05\x03\x06\x03\x02\x01\x02\x03\xff\x01\x00\x01\x00\x00\x12\x00\x00\x00+\x00\t\x08\x03\x04\x03\x03\x03\x02\x03\x01\x003\x00&\x00$\x00\x1d\x00 Ue\xee\xf2\xe1\xff\xc1>\x14\xa7\r\xdeR<L\xec\xec-\n8p\x97\xf5\xe5\x07\xe3\xc9\x99w\xc3t\x19'
- Choked at offset 12 while unpacking b'\x0c."j\x05r\x0c\x1b\x1b\x01;\x04XG7\r'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
    self.read_questions()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
    name = self.read_name()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
    raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 115 is unknown at 12
```

- struct.error: unpack requires a buffer of 12 bytes
```shell
Logger: zeroconf
Source: /usr/local/lib/python3.9/site-packages/zeroconf/_logger.py:52
First occurred: 19 septembre 2021, 13:12:11 (1 occurrences)
Last logged: 19 septembre 2021, 13:12:11

Choked at offset 0 while unpacking b'P.ki^\x08t\x16\xd7'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 109, in __init__
    self.read_header()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 146, in read_header
    ) = self.unpack(b'!6H')
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 133, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
```

- zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
```shell
Logger: zeroconf
Source: /usr/local/lib/python3.9/site-packages/zeroconf/_logger.py:52
First occurred: 19 septembre 2021, 2:33:43 (1 occurrences)
Last logged: 19 septembre 2021, 2:33:43

Choked at offset 12 while unpacking b'#.(\x1d\nU62td\x08\x01#\x10zA\x03\x06Y1R\x17}<@\x16mzc/8\x07\x1d`$\'5ZY)>a+bq%#u,|&~W"'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
    self.read_questions()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
    name = self.read_name()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 309, in _decode_labels_at_offset
    raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
```

#### Log details per message

<details><summary>IncomingDecodeError: DNS compression type 115 is unknown at 12</summary>

```shell
2021-09-18 23:30:06 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b'\\.>v~2Z\x17k\x14Yes/B1DC \\H`Ij$:s\x12qbrNJ0DIb\x1e`N393&huW,8w1\x14'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 115 is unknown at 12
```

</details>

<details><summary>IncomingDecodeError: DNS compression type 109 is unknown at 25</summary>

```shell
2021-09-18 23:35:29 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b'6.Y^:VN\x0cH\x0f}G\nt&;\x1dtBMn*\\\x01km6<\xa7\xcd'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 109 is unknown at 25
```

</details>

<details><summary>IncomingDecodeError: Corrupt packet received while decoding name</summary>

```shell
2021-09-19 00:33:43 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b'#.(\x1d\nU62td\x08\x01#\x10zA\x03\x06Y1R\x17}<@\x16mzc/8\x07\x1d`$\'5ZY)>a+bq%#u,|&~W"'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 309, in _decode_labels_at_offset
raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
```

</details>

<details><summary>struct.error: unpack requires a buffer of 12 bytes</summary>

```shell
2021-09-19 11:12:11 WARNING (MainThread) [zeroconf] Choked at offset 0 while unpacking b'P.ki^\x08t\x16\xd7'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 109, in __init__
self.read_header()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 146, in read_header
) = self.unpack(b'!6H')
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 133, in unpack
info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
```

</details>

<details><summary>IncomingDecodeError: DNS compression type 72 is unknown at 12</summary>

```shell
2021-09-19 16:16:19 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b"}.+u\x1f!]Kl wSH)H?nj<XK3E*\x13\n&9\x11\x10i\x0f$\x14\x04D5b\x0f!\x02\x06tJ0=\n\x1e'Fwry<\x1d\x0cFCEWS.fxCk<xMK\x1aOQ\x0e\x1a\x01Ki\xce"
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 72 is unknown at 12
```

</details>

<details><summary>IncomingDecodeError: DNS compression type 116 is unknown at 60</summary>

```shell
2021-09-19 19:45:57 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b"y.{\x00'|S:qw\x15\x17/\x7fwGad\x17;D@5\t#\x7f\x1f\x13p\x1fld\x135mZ\x021a\n\x12bh`\r=;\x06\x04Z\x19\x07f?\x055Ra.;t"
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 116 is unknown at 60
```

</details>

<details><summary>IncomingDecodeError: DNS compression type 104 is unknown at 12</summary>

```shell
2021-09-19 22:33:45 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b'\x16\x03\x01\x00\xee\x01\x00\x00\xea\x03\x03whv\xe7\xb7\xc4@\xb7\xbe\xc0\xba\x1911~\xb6\x1f)U\xff\x967\xb4F\xe1\xf3\x85%\x97Q\xd7\xa1 K\x0f\x86\x11/\x9fk\xcd\xfeWi)r\xcc\xeb\x16\xb5\xa3yx)R\xec\xb3V\x02B\xa7\x8e\xa2E\xfe\x00&\xc0/\xc00\xc0+\xc0,\xcc\xa8\xcc\xa9\xc0\x13\xc0\t\xc0\x14\xc0\n\x00\x9c\x00\x9d\x00/\x005\xc0\x12\x00\n\x13\x01\x13\x03\x13\x02\x01\x00\x00{\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\n\x00\n\x00\x08\x00\x1d\x00\x17\x00\x18\x00\x19\x00\x0b\x00\x02\x01\x00\x00\r\x00\x1a\x00\x18\x08\x04\x04\x03\x08\x07\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x05\x03\x06\x03\x02\x01\x02\x03\xff\x01\x00\x01\x00\x00\x12\x00\x00\x00+\x00\t\x08\x03\x04\x03\x03\x03\x02\x03\x01\x003\x00&\x00$\x00\x1d\x00 Ue\xee\xf2\xe1\xff\xc1>\x14\xa7\r\xdeR<L\xec\xec-\n8p\x97\xf5\xe5\x07\xe3\xc9\x99w\xc3t\x19'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 104 is unknown at 12
```

</details>

<details><summary>IncomingDecodeError: DNS compression type 88 is unknown at 12</summary>

```shell
2021-09-20 03:43:27 WARNING (MainThread) [zeroconf] Choked at offset 12 while unpacking b'\x0c."j\x05r\x0c\x1b\x1b\x01;\x04XG7\r'
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 110, in __init__
self.read_questions()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 151, in read_questions
name = self.read_name()
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 268, in read_name
self.offset = self._decode_labels_at_offset(self.offset, labels)
File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol.py", line 289, in _decode_labels_at_offset
raise IncomingDecodeError(f"DNS compression type {length} is unknown at {off}")
zeroconf._exceptions.IncomingDecodeError: DNS compression type 88 is unknown at 12
```

</details>

### Additional information

May be linked to #308

**Comment by bdraco** [comment]
Something on your network is broadcasting invalid mdns packets.  There isn't anything zeroconf can do about this as the packets are malformed, and the warning is expected.

dnspython agrees:

```
% python3
Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.message
>>> dns.message.from_wire(b'6.Y^:VN\x0cH\x0f}G\nt&;\x1dtBMn*\\\x01km6<\xa7\xcd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 1074, in from_wire
    m = reader.read()
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 995, in read
    self._get_question(MessageSection.QUESTION, qcount)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 896, in _get_question
    qname = self.parser.get_name(self.message.origin)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/wire.py", line 52, in get_name
    name = dns.name.from_wire_parser(self)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/name.py", line 989, in from_wire_parser
    raise BadLabelType
dns.name.BadLabelType: The label type in DNS name wire format is unknown.
>>> dns.message.from_wire(b"}.+u\x1f!]Kl wSH)H?nj<XK3E*\x13\n&9\x11\x10i\x0f$\x14\x04D5b\x0f!\x02\x06tJ0=\n\x1e'Fwry<\x1d\x0cFCEWS.fxCk<xMK\x1aOQ\x0e\x1a\x01Ki\xce")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 1074, in from_wire
    m = reader.read()
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 995, in read
    self._get_question(MessageSection.QUESTION, qcount)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 896, in _get_question
    qname = self.parser.get_name(self.message.origin)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/wire.py", line 52, in get_name
    name = dns.name.from_wire_parser(self)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/name.py", line 989, in from_wire_parser
    raise BadLabelType
dns.name.BadLabelType: The label type in DNS name wire format is unknown.
>>> dns.message.from_wire(b"y.{\x00'|S:qw\x15\x17/\x7fwGad\x17;D@5\t#\x7f\x1f\x13p\x1fld\x135mZ\x021a\n\x12bh`\r=;\x06\x04Z\x19\x07f?\x055Ra.;t")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 1074, in from_wire
    m = reader.read()
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 995, in read
    self._get_question(MessageSection.QUESTION, qcount)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/message.py", line 896, in _get_question
    qname = self.parser.get_name(self.message.origin)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/wire.py", line 52, in get_name
    name = dns.name.from_wire_parser(self)
  File "/opt/homebrew/lib/python3.9/site-packages/dns/name.py", line 989, in from_wire_parser
    raise BadLabelType
dns.name.BadLabelType: The label type in DNS name wire format is unknown.
>>> 
```

**Comment by bdraco** [comment]
We get an issue about this once a month.  I'm going to re-work the message to make it clear where the invalid packet is coming from as its not very obvious and the choked wording makes it seems like there is a problem in zeroconf.

**Comment by bdraco** [comment]
#998 will improve the log message and log the source of the invalid data
